language: php

php:
  - 5.6
  - 7.0

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" < "7.0" ]]; then pecl install pthreads-2.0.10; fi
  - if [[ "$TRAVIS_PHP_VERSION" = "7.0" ]] || [[ "$TRAVIS_PHP_VERSION" > "7.0" ]]; then pecl install pthreads-3.1.6; fi
  - phpenv rehash
  - wget https://scrutinizer-ci.com/ocular.phar
  - wget https://getcomposer.org/composer.phar

script:
  - php -d memory_limit=-1 composer.phar update
  - vendor/bin/robo build

env:
  global:
    - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      language: ruby
      before_install:
        - brew update
        - brew install ant
        - wget https://getcomposer.org/composer.phar
      script:
        - php -d memory_limit=-1 composer.phar install
        - sudo chown $USER /opt
        - ant dependencies-init -f vendor/appserver-io-dist/osx/build.xml
        - ant local-build -Dos.family=mac -f vendor/appserver-io-dist/osx/build.xml
        - mv vendor/appserver-io-dist/osx/build/* build/
        - if [[ "$TRAVIS_TAG" ]]; then echo "TAGGED"; fi
    - os: linux
      dist: xenial
      php: 5.6
      services:
        - docker
      script:
        - echo "debian"
  allow_failures:
    - php: 7.0

deploy:
  provider: releases
  api_key:
    secure: "T/+tptqFVgBCPgVPQqEL7ciWg5N4hp4bWdq9jG7AIB3K1inu1LL4HzggOfyeSktUOW63SZdEoWqrXaYk0d4+4f811Dzign3Eqi/m/yw2Opwh0jbpOTvaQBZfN8/xBAB9/TfsPyFWq4buF8fI5Njew7wbxs/n1c701L2zFtzmxEM="
  file_glob: true
  file: "build/*"
  skip_cleanup: true
  on:
    tags: true
    branch: '1.1'
    repo: wick-ed/appserver

notifications:
  email: info@appserver.io
  webhooks: https://app.fossa.io/hooks/travisci
