language: php

php:
  - 5.6
  - 7.0

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" < "7.0" ]]; then pecl install pthreads-2.0.10; fi
  - if [[ "$TRAVIS_PHP_VERSION" = "7.0" ]] || [[ "$TRAVIS_PHP_VERSION" > "7.0" ]]; then pecl install pthreads-3.1.6; fi
  - phpenv rehash
  - wget https://scrutinizer-ci.com/ocular.phar
  - wget https://getcomposer.org/composer.phar

script:
  - php -d memory_limit=-1 composer.phar update
  - vendor/bin/robo build

env:
  global:
    - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env: OS_FAMILY = mac
      script:
        - echo "macos"
        - php -v
    - os: linux
      dist: xenial
      php: 5.6
      env:
        - OS_FAMILY = linux
        - OS_DISTRO = debian
      services:
        - docker
      script:
        - mkdir -p build
        - composer install
        - docker run --rm -v `pwd`:/build -w /build debian:9 bash -c "apt-get update; apt-get install -y ant git php; ant dependencies-init -f vendor/appserver-io-dist/debian/build.xml; ant local-build -Dbuild.number=$BUILD_NUMBER -Dtarget-os.major.version=9 -Dtarget-os.minor.version=9 -f vendor/appserver-io-dist/debian/build.xml; chmod -R 777 vendor/appserver-io-dist/debian/build"
        - mv vendor/appserver-io-dist/debian/build/* build/
        - if [[ "$TRAVIS_TAG" ]]; then echo "TAGGED"; fi
  allow_failures:
    - php: 7.0

deploy:
  provider: releases
  api_key:
    secure: "T/+tptqFVgBCPgVPQqEL7ciWg5N4hp4bWdq9jG7AIB3K1inu1LL4HzggOfyeSktUOW63SZdEoWqrXaYk0d4+4f811Dzign3Eqi/m/yw2Opwh0jbpOTvaQBZfN8/xBAB9/TfsPyFWq4buF8fI5Njew7wbxs/n1c701L2zFtzmxEM="
  file_glob: true
  file: "build/*"
  skip_cleanup: true
  on:
    tags: true
    branch: '1.1'
    repo: wick-ed/appserver
